### ISSUE TITLE
"Panel plugin not found: grafana-piechart-panel"

### ISSUE THREAD

**Issue by holmesb** [tcheronneau/grafana_dashboard#1]
"Panel plugin not found: grafana-piechart-panel" error displayed in many traefik panels on Grafana  v7.5.5

**Comment by tcheronneau** [comment]
Hey, 
Sorry it's been a while I did not check this dashboard in fact. 
I'll try to update it. But in the meantime do you have the plugin or can you try to install it ?

**Comment by tcheronneau** [comment]
Indeed it was not working since the plugin is deprecated. 
I've updated it on grafana.com + this repo. 
Also updated because Traefik changed a lot since the first release.
